[package]
name = "fp"
version = "0.1.0"
authors = ["aaqib-kk <aqib.khan.25@iiee.edu.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reqwest = "0.9.22"
reqwest = { version = "0.10", features = ["json"] }